learning_log/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
from django.urls import path, include
from . import views


app_name = 'learning_logs'
#app_name = 'users'
urlpatterns = [
    # Домашняя страница
    path('', views.index, name='index'),
    # Страница с подробной информацией по отдельной теме
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    # Страница со списком всех тем.
    path('topics/', views.topics, name='topics'),
    # Страница для добавления новой темы
    path('new_topic/', views.new_topic, name='new_topic'),
    # Страница для добавления новой записи
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Страница для редактирования записи
    path('edit_entry/<int:entry_id>/', views.edit_entry, name='edit_entry'),

]

users/urls.py
"""Определяет схемы URL для пользователей"""
from django.urls import path, include
from . import views
app_name = 'users'
urlpatterns = [
    # Включить URL авторизации по умолчанию.
    path('', include('django.contrib.auth.urls')),
    # Страница регистрации.
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
...
class Topic(models.Model):
    """Тема, которую изучает пользователь"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Возвращает строковое представление модели."""
        return self.text


class Entry(models.Model):
    """Информация, изученная пользователем по теме"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Возвращает строковое представление модели."""
        return f"{self.text[:50]}..."

users/models.py
from django.db import models

# Create your models here.

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': 'Entry:'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .models import Topic, Entry
from .forms import TopicForm, EntryForm

@login_required
# Create your views here.
def index(request):
    """Домашняя страница приложения Learning Log"""
    return render(request, 'learning_logs/index.html')

@login_required
def topic(request, topic_id):
    """Выводит одну тему и все ее записи."""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)
@login_required
def topics(request):
    """Выводит список тем."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)



@login_required
def new_topic(request):
    """Определяет новую тему."""
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = TopicForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = TopicForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topics')
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """Добавляет новую запись по конкретной теме."""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # Данные не отправлялись; создается пустая форма.
        form = EntryForm()
    else:
        # Отправлены данные POST; обработать данные.
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return redirect('learning_logs:topic', topic_id=topic_id)
    # Вывести пустую или недействительную форму.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """Редактирует существующую запись."""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if request.method != 'POST':
        # Исходный запрос; форма заполняется данными текущей записи.
        form = EntryForm(instance=entry)
    else:
        # Отправка данных POST; обработать данные.
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login
from django.contrib.auth.forms import UserCreationForm


def register(request):
    """Регистрирует нового пользователя."""
    if request.method != 'POST':
        # Выводит пустую форму регистрации.
        form = UserCreationForm()
    else:
        # Обработка заполненной формы.
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            # Выполнение входа и перенаправление на домашнюю страницу.
            login(request, new_user)
            return redirect('learning_logs:index')
    # Вывести пустую или недействительную форму.
    context = {'form': form}
    return render(request, 'registration/register.html', context)

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<title>Learning Log</title>
	{% bootstrap_css %}
	{% bootstrap_javascript jquery='full' %}
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark mb-4">
	<a class="navbar-brand" href="{% url 'learning_logs:index' %}">
		Learning Log</a>
	<button class="navbar-toggler" type="button" data-toggle="collapse"
			data-target="#navbarCollapse" aria-controls="navbarCollapse"
			aria-expanded="false" aria-label="Toggle navigation">
		<span class="navbar-toggler-icon"></span></button>
	<div class="collapse navbar-collapse" id="navbarCollapse">
		<ul class="navbar-nav mr-auto">
			<li class="nav-item">
				<a class="nav-link" href="{% url 'learning_logs:topics' %}">
					Topics</a></li>
		</ul>
		<ul class="navbar-nav ml-auto">
			{% if user.is_authenticated %}
				<li class="nav-item">
					<span class="navbar-text"> Hello, {{ user.username }}.</span>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:logout' %}">Log out</a>
				</li>
			{% else %}
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:register' %}">Register</a>
				</li>
				<li class="nav-item">
					<a class="nav-link" href="{% url 'users:login' %}">Log in</a></li>
			{% endif %}
		</ul>
	</div>
</nav>
<main role="main" class="container">
	<div class="pb-2 mb-2 border-bottom">
		{% block page_header %}{% endblock page_header %}
	</div>
	<div>
		{% block content %}{% endblock content %}
	</div>
</main>
</body>
</html>

learning_logs/templates/learning_logs/edit_entry.html
{#{% extends "learning_logs/base.html" %}#}
{#{% block content %}#}
{#	<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>#}
{#	<p>Edit entry:</p>#}
{#		<form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'>#}
{#		{% csrf_token %}#}
{#		{{ form.as_p }}#}
{#		<button name="submit">save changes</button>#}
{#	</form>#}
{#{% endblock content %}#}
{##}


{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>Edit entry</h2>
{% endblock page_header %}

{% block content %}
	<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
	  <form method="post" action="{% url 'learning_logs:edit_entry' entry.id %}" class="form">

		  {% csrf_token %}
		  {% bootstrap_form form %}

		  {% buttons %}
			<button name="submit" class="btn btn-primary">Save</button>
		  {% endbuttons %}

		<input type="hidden" name="next" value="{% url 'learning_logs:topics' %}" />
	  </form>
{% endblock content %}

learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
    {% block content %}
    <p>Learning Log helps you!</p>
    {% endblock content %}

learning_logs/templates/learning_logs/new_entry.html
{#{% extends "learning_logs/base.html" %}#}
{#{% block content %}#}
{#  <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>#}
{#  <p>Add a new entry:</p>#}
{#  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'>#}
{#    {% csrf_token %}#}
{#    {{ form.as_p }}#}
{#    <button name='submit'>add entry</button>#}
{#  </form>#}
{#{% endblock content %}#}
{#---#}

{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>New entry</h2>
{% endblock page_header %}

{% block content %}
	<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>
	  <form method="post" action="{% url 'learning_logs:new_entry' topic.id %}" class="form">

		  {% csrf_token %}
		  {% bootstrap_form form %}

		  {% buttons %}
			<button name="submit" class="btn btn-primary">Create</button>
		  {% endbuttons %}

		<input type="hidden" name="next" value="{% url 'learning_logs:topics' %}" />
	  </form>
{% endblock content %}

learning_logs/templates/learning_logs/new_topic.html
{#{% extends "learning_logs/base.html" %}#}
{#{% block content %}#}
{##}
{#	<p>Add a new topic:</p>#}
{#	<form action="{% url 'learning_logs:new_topic' %}" method='post'>#}
{#	{% csrf_token %}#}
{#		{{ form.as_p }}#}
{#		<button name="submit">add topic</button>#}
{#	</form>#}
{##}
{#{% endblock content %}#}
{##}
{##}
{#---#}

{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
  <h2>New topic</h2>
{% endblock page_header %}

{% block content %}
	  <form method="post" action="{% url 'learning_logs:new_topic'%}" class="form">

		  {% csrf_token %}
		  {% bootstrap_form form %}

		  {% buttons %}
			<button name="submit" class="btn btn-primary">Create</button>
		  {% endbuttons %}

{#		<input type="hidden" name="next" value="{% url 'learning_logs:topics' %}" />#}
	  </form>
{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends 'learning_logs/base.html' %}
{#{% block content %}#}
{#  <p>Topic: {{ topic }}</p>#}
{#  <p>Entries:</p>#}
{#	<p>#}
{#    	<a href="{% url 'learning_logs:new_entry' topic.id %}">add new entry</a>#}
{#  	</p>#}
{#  <ul>#}
{#  {% for entry in entries %}#}
{#    <li>#}
{#      <p>{{ entry.date_added|date:'F d, Y H:i' }}</p>#}
{#      <p>{{ entry.text|linebreaksbr }}</p>#}
{#		<p>#}
{#            <a href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a>#}
{#        </p>#}
{#    </li>#}
{#  {% empty %}#}
{#    <li>There are no entries for this topic yet ¯\_(ツ)_/¯</li>#}
{#  {% endfor %}#}
{#  </ul>#}
{#{% endblock content %}#}
{##}
{#--#}


{% block page_header %}
  <h3>{{ topic }}</h3>
{% endblock page_header %}
{% block content %}
  <p>
<a class="btn btn-outline-info" href="{% url 'learning_logs:new_entry' topic.id %}">Add new entry</a>
  </p>
  {% for entry in entries %}
    <div class="card mb-3">
      <h4 class="card-header">
        {{ entry.date_added|date:'F d, Y H:i' }}
        <small><a class="btn btn-outline-info" href="{% url 'learning_logs:edit_entry' entry.id %}">Edit entry</a></small>
      </h4>
      <div class="card-body">
        {{ entry.text|linebreaks }}
      </div>
    </div>
{% empty %}
    <p>There are no entries for this topic yet ¯\_(ツ)_/¯</p>
  {% endfor %}
{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}
{#{% block content %}#}
{#  <p>Topics</p>#}
{#  <ul>#}
{#    {% for topic in topics %}#}
{#		<li>#}
{#            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>#}
{#		</li>#}
{#    {% empty %}#}
{#      <li>No topics ¯\_(ツ)_/¯</li>#}
{#    {% endfor %}#}
{#  </ul>#}
{#	<a href="{% url 'learning_logs:new_topic' %}">Add a new topic:</a>#}
{#{% endblock content %}#}
{##}
{#--#}


{% block page_header %} <h1>Topics</h1>
{% endblock page_header %}
{% block content %}

	{% for topic in topics %}
		<div class="card" style="width: 100%;">
			<ul class="list-group list-group-flush">
				<li class="list-group-item">
					<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
				</li>
			</ul>
		</div>
	{% empty %}
			<li><h4>No topics ¯\_(ツ)_/¯</h4></li>
	{% endfor %}


{#	<ul>#}
{#		{% for topic in topics %}#}
{#			<li>#}
{#				<h5>#}
{#					<a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>#}
{#				</h5>#}
{#			</li>#}
{#		{% empty %}#}
{#			<li><h4>No topics ¯\_(ツ)_/¯</h4></li>#}
{#		{% endfor %}#}
{#	</ul>#}
	<br>
	<a class="btn btn-outline-info" href="{% url 'learning_logs:new_topic' %}"> Add new topic</a>
{% endblock content %}